version: '3.8'

services:
  frontend:
    build: ./frontend
    container_name: todo_frontend
    ports:
      - '3000:3000'
    volumes:
      - './frontend:/app'
      - '/app/node_modules'
    environment:
      - NODE_ENV=development
      - CHOKIDAR_USEPOLLING=true
    depends_on:
      - backend

  backend:
    build: ./backend
    container_name: todo_backend
    ports:
      - '5000:5000'
    volumes:
      - './backend:/app'
      - '/app/node_modules'
    environment:
      - PORT=5000
      - PGUSER=postgres
      - PGPASSWORD=postgres
      - PGHOST=db
      - PGPORT=5432
      - PGDATABASE=tododb
    depends_on:
      - db

  db:
    image: postgres:13
    container_name: todo_db
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: tododb
    volumes:
      - 'todo_db_data:/var/lib/postgresql/data'
      - './backend/db-init.sql:/docker-entrypoint-initdb.d/db-init.sql'

volumes:
  todo_db_data:
